name: PluginSDG
version: 1.0
main: moe.sdg.PluginSDG.GameManager
depend: [WorldEdit]
api-version: 1.16
commands:
  hub:
    description: Return to the hub
    usage: /<command>
  sethub:
    description: Set the hub location
    usage: /<command>
  sdg:
    description: Base command for games
    usage: /<command> <param>